version: 2
jobs:
  build:
    working_directory: ~/ionic/
    docker:
      - image: node:8
    branches:
      # ignore:
      #   - core
    steps:
      - checkout
      - restore_cache:
         key: node_modules_{{ checksum "package.json" }}
      - run:
         name: Install monorepo node modules
         command: npm i
      - save_cache:
         key: node_modules_{{ checksum "package.json" }}
         paths:
         - ~/ionic/node_modules/
      - restore_cache:
         key: node_modules_{{ checksum "core/package.json" }}
      - run:
         name: Install core node modules
         command: npm --prefix core/ i
      - save_cache:
         key: node_modules_{{ checksum "core/package.json" }}
         paths:
         - ~/ionic/core/node_modules/
      - run:
          name: Validate Core
          command: npm --prefix core/ run validate
